
#include <stdio.h>
#include <errno.h>
#include <asm-generic/errno.h>

#define ERR_LIST_ENTRY(x) \
    [x] = #x

static char* g_error_lookup_table[] = {
    [0] = "NOERROR",

ERR_LIST_ENTRY(E2BIG),
ERR_LIST_ENTRY(EACCES),
ERR_LIST_ENTRY(EADDRINUSE),
ERR_LIST_ENTRY(EADDRNOTAVAIL),
ERR_LIST_ENTRY(EAFNOSUPPORT),
ERR_LIST_ENTRY(EAGAIN),
ERR_LIST_ENTRY(EALREADY),
ERR_LIST_ENTRY(EBADE),
ERR_LIST_ENTRY(EBADF),
ERR_LIST_ENTRY(EBADFD),
ERR_LIST_ENTRY(EBADMSG),
ERR_LIST_ENTRY(EBADR),
ERR_LIST_ENTRY(EBADRQC),
ERR_LIST_ENTRY(EBADSLT),
ERR_LIST_ENTRY(EBUSY),
ERR_LIST_ENTRY(ECANCELED),
ERR_LIST_ENTRY(ECHILD),
ERR_LIST_ENTRY(ECHRNG),
ERR_LIST_ENTRY(ECOMM),
ERR_LIST_ENTRY(ECONNABORTED),
ERR_LIST_ENTRY(ECONNREFUSED),
ERR_LIST_ENTRY(ECONNRESET),
ERR_LIST_ENTRY(EDEADLK),
ERR_LIST_ENTRY(EDEADLOCK),
ERR_LIST_ENTRY(EDESTADDRREQ),
ERR_LIST_ENTRY(EDOM),
ERR_LIST_ENTRY(EDQUOT),
ERR_LIST_ENTRY(EEXIST),
ERR_LIST_ENTRY(EFAULT),
ERR_LIST_ENTRY(EFBIG),
ERR_LIST_ENTRY(EHOSTDOWN),
ERR_LIST_ENTRY(EHOSTUNREACH),
ERR_LIST_ENTRY(EHWPOISON),
ERR_LIST_ENTRY(EIDRM),
ERR_LIST_ENTRY(EILSEQ),
ERR_LIST_ENTRY(EINPROGRESS),
ERR_LIST_ENTRY(EINTR),
ERR_LIST_ENTRY(EINVAL),
ERR_LIST_ENTRY(EIO),
ERR_LIST_ENTRY(EISCONN),
ERR_LIST_ENTRY(EISDIR),
ERR_LIST_ENTRY(EISNAM),
ERR_LIST_ENTRY(EKEYEXPIRED),
ERR_LIST_ENTRY(EKEYREJECTED),
ERR_LIST_ENTRY(EKEYREVOKED),
ERR_LIST_ENTRY(EL2HLT),
ERR_LIST_ENTRY(EL2NSYNC),
ERR_LIST_ENTRY(EL3HLT),
ERR_LIST_ENTRY(EL3RST),
ERR_LIST_ENTRY(ELIBACC),
ERR_LIST_ENTRY(ELIBBAD),
ERR_LIST_ENTRY(ELIBMAX),
ERR_LIST_ENTRY(ELIBSCN),
ERR_LIST_ENTRY(ELIBEXEC),
// ERR_LIST_ENTRY(ELNRANGE),
ERR_LIST_ENTRY(ELOOP),
ERR_LIST_ENTRY(EMEDIUMTYPE),
ERR_LIST_ENTRY(EMFILE),
ERR_LIST_ENTRY(EMLINK),
ERR_LIST_ENTRY(EMSGSIZE),
ERR_LIST_ENTRY(EMULTIHOP),
ERR_LIST_ENTRY(ENAMETOOLONG),
ERR_LIST_ENTRY(ENETDOWN),
ERR_LIST_ENTRY(ENETRESET),
ERR_LIST_ENTRY(ENETUNREACH),
ERR_LIST_ENTRY(ENFILE),
ERR_LIST_ENTRY(ENOANO),
ERR_LIST_ENTRY(ENOBUFS),
ERR_LIST_ENTRY(ENODATA),
ERR_LIST_ENTRY(ENODEV),
ERR_LIST_ENTRY(ENOENT),
ERR_LIST_ENTRY(ENOEXEC),
ERR_LIST_ENTRY(ENOKEY),
ERR_LIST_ENTRY(ENOLCK),
ERR_LIST_ENTRY(ENOLINK),
ERR_LIST_ENTRY(ENOMEDIUM),
ERR_LIST_ENTRY(ENOMEM),
ERR_LIST_ENTRY(ENOMSG),
ERR_LIST_ENTRY(ENONET),
ERR_LIST_ENTRY(ENOPKG),
ERR_LIST_ENTRY(ENOPROTOOPT),
ERR_LIST_ENTRY(ENOSPC),
ERR_LIST_ENTRY(ENOSR),
ERR_LIST_ENTRY(ENOSTR),
ERR_LIST_ENTRY(ENOSYS),
ERR_LIST_ENTRY(ENOTBLK),
ERR_LIST_ENTRY(ENOTCONN),
ERR_LIST_ENTRY(ENOTDIR),
ERR_LIST_ENTRY(ENOTEMPTY),
ERR_LIST_ENTRY(ENOTRECOVERABLE),
ERR_LIST_ENTRY(ENOTSOCK),
ERR_LIST_ENTRY(ENOTSUP),
ERR_LIST_ENTRY(ENOTTY),
ERR_LIST_ENTRY(ENOTUNIQ),
ERR_LIST_ENTRY(ENXIO),
ERR_LIST_ENTRY(EOPNOTSUPP),
ERR_LIST_ENTRY(EOVERFLOW),
ERR_LIST_ENTRY(EOWNERDEAD),
ERR_LIST_ENTRY(EPERM),
ERR_LIST_ENTRY(EPFNOSUPPORT),
ERR_LIST_ENTRY(EPIPE),
ERR_LIST_ENTRY(EPROTO),
ERR_LIST_ENTRY(EPROTONOSUPPORT),
ERR_LIST_ENTRY(EPROTOTYPE),
ERR_LIST_ENTRY(ERANGE),
ERR_LIST_ENTRY(EREMCHG),
ERR_LIST_ENTRY(EREMOTE),
ERR_LIST_ENTRY(EREMOTEIO),
ERR_LIST_ENTRY(ERESTART),
ERR_LIST_ENTRY(ERFKILL),
ERR_LIST_ENTRY(EROFS),
ERR_LIST_ENTRY(ESHUTDOWN),
ERR_LIST_ENTRY(ESPIPE),
ERR_LIST_ENTRY(ESOCKTNOSUPPORT),
ERR_LIST_ENTRY(ESRCH),
ERR_LIST_ENTRY(ESTALE),
ERR_LIST_ENTRY(ESTRPIPE),
ERR_LIST_ENTRY(ETIME),
ERR_LIST_ENTRY(ETIMEDOUT),
ERR_LIST_ENTRY(ETOOMANYREFS),
ERR_LIST_ENTRY(ETXTBSY),
ERR_LIST_ENTRY(EUCLEAN),
ERR_LIST_ENTRY(EUNATCH),
ERR_LIST_ENTRY(EUSERS),
// ERR_LIST_ENTRY(EWOULDBLOCK), // overlaps
ERR_LIST_ENTRY(EXDEV),
ERR_LIST_ENTRY(EXFULL)
};

#undef ERR_LIST_ENTRY

char* lookup_errname(int err) {
    char* returnstr = "";
    // change to positive if a negative value was passed
    if (err < 0) {
        err = -err;
    }

    if (err > (sizeof(g_error_lookup_table)/sizeof(char*))-1) {
        returnstr = "Out of bounds";
        goto exit;
    }

    returnstr = g_error_lookup_table[err];
    if (returnstr == NULL) {
        returnstr = "Undefined";
    }
exit:
    return returnstr;
}

void err_lookup_test(void) {
    for (int i = 0; i < (sizeof(g_error_lookup_table)/sizeof(char*)) + 1; i++) {
        printf("%s %d\n", lookup_errname(i), i);
    }
    return;
}

